#!/bin/bash
#gplv3 by https://github.com/lnee94
#note functnality has been removed because it is not ready
setup(){
case "$1" in

    
  sel)
    id="$(xdotool selectwindow)"
    ;;

  *)
    feh -x ~/.face.icon & 
    sleep 0.6
    id="$(xdotool search --pid "$(jobs -p | tail -1)" )"
    ;;
esac



echo "$id"
}


gety(){ 
xdotool getwindowgeometry "$id" |head -2 | tail -1 | awk -F, '{print $2}' | awk '{print $1}'
}

mowin(){
local tmp 
tmp=$(($old+$1))
if [ $tmp -gt $gr ] && [ $tmp -lt 1000 ]
then
tmp=$gr
fi
if [ $tmp -lt $cel ]
then
tmp=$cel
fi

xdotool windowmove "$id" x "$tmp"
}

setup $1
bgr=932
gr=$bgr
cel=400
old=$(gety)

v=0
g=4

while true
do


old=$(gety)
echo $v "$old" "$gr" "$cel" $$ $id $vx $iii 
mowin $(($v+$g))
v=$(($v+$g))

if [ $(($(gety)-$old)) = 0 ]
then
if [ $v -gt 10 ]
then
v=$((($v*-1)+13))
else
v=0
fi
fi





done
